services:
  #  APPS
  ahmed:
    build: .
    ports:
      - "8081:8080"
    environment:
      Instance: "Instance 1"
      spring.data.mongodb.uri: mongodb://ahmed:13398@mongo:27017/ahmed_52_13398?authSource=admin
      spring.data.mongodb.database: ahmed_52_13398

  gabr:
    build: .
    ports:
      - "8082:8080"
    environment:
      Instance: "Instance 2"
      spring.data.mongodb.uri: mongodb://ahmed:13398@mongo:27017/ahmed_52_13398?authSource=admin
      spring.data.mongodb.database: ahmed_52_13398
  # MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahmed
      MONGO_INITDB_ROOT_PASSWORD: 13398
      MONGO_INITDB_DATABASE: ahmed_52_13398
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ahmed
      ME_CONFIG_MONGODB_ADMINPASSWORD: 13398
      ME_CONFIG_MONGODB_URL: mongodb://ahmed:13398@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  # Nginx
  nginx:
    image: nginx
    ports:
      - "13398:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ahmed
      - gabr